###
curl http://localhost:8080/albums
###
curl http://localhost:8080/albums/4
###
curl -X "DELETE" http://localhost:8080/albums/2
###
curl http://localhost:8080/albums \
    --include \
    --header "Content-Type: application/json" \
    --request "POST" \
    --data '{"id": "1", "firstname": "Naruto", "lastname": "Uzumake", "email": "konoha-uzumake@mail.com", "age": 18, "created": time.Now()}'

###
curl -X "PUT" http://localhost:8080/albums/1 \
    --include \
    --header "Content-Type: application/json" \
    --request "POST" \
    --data '{"id": "3","firstname": "Madara","created": "time.Now()"}'

